version: "3"
services:
  postgresql:
    image: "postgres:13.10-alpine"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=elk
      - POSTGRES_DB=elk
    ports:
      - 5432:5432
  chat-room-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatroom-api
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgresql
    expose:
      - 3000